version: "3.2"

services:
    authorsapi:
        container_name: authorsapi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8090:8000
        volumes:
            - ../LumenAuthorsApi:/src

    booksapi:
        container_name: booksapi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8091:8000
        volumes:
            - ../LumenBooksApi:/src

    apigateway:
        container_name: apigateway
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8092:8000
        volumes:
            - ../LumenApiGateway:/src